FROM python:3.9

ARG PYTORCH_VERSION=2.0.1
ARG TORCHVISION_VERSION==0.15.2
ARG TORCH_CPU_URL=https://download.pytorch.org/whl/cpu/torch_stable.html

RUN \
    python -m pip install --no-cache-dir \
    torch==${PYTORCH_VERSION}+cpu \
    torchvision==${TORCHVISION_VERSION}+cpu -f ${TORCH_CPU_URL}

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

EXPOSE 8080

COPY ["server_vit.py", "model_vit.script.pt", "."]

CMD ["uvicorn", "server_vit:app", "--host", "0.0.0.0", "--port", "8080"]